# Generated by Django 5.1.2 on 2025-09-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pig',
            name='description',
        ),
    ]
