# Generated by Django 5.1.2 on 2025-09-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_pig_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(blank=True, help_text='Date when pig will be picked up or delivered', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(blank=True, help_text='Time when pig will be picked up or delivered', null=True),
        ),
    ]
