# Generated by Django 5.1.2 on 2025-10-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
