# Generated by Django 5.1.2 on 2025-10-21 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Required down payment amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('pig_breed', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=200)),
                ('payment_method', models.CharField(max_length=10)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.reservation')),
            ],
            options={
                'ordering': ['-completed_date'],
            },
        ),
    ]
