# Generated by Django 5.1.2 on 2025-10-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_reservation_down_payment_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash')], max_length=10),
        ),
    ]
