# Generated by Django 5.1.2 on 2025-10-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('unread', 'Unread'), ('read', 'Read'), ('replied', 'Replied')], default='unread', max_length=10),
        ),
    ]
