# Generated by Django 5.1.2 on 2025-10-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig',
            name='description',
            field=models.TextField(blank=True, help_text="Short description of the pig's characteristics"),
        ),
    ]
