# Generated by Django 5.1.2 on 2025-10-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_paymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Indicates if the customer has paid for this reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='delivery_option',
            field=models.CharField(choices=[('home', 'Delivery'), ('pickup', 'Pick up at Farm')], max_length=10),
        ),
    ]
