# Generated by Django 5.1.2 on 2025-11-13 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_reservation_status_declinenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits starting with 09.', regex='^09\\d{9}$')]),
        ),
    ]
